global:
  scrape_interval: 15s # 默认15s 全局每次数据收集的间隔
  evaluation_interval: 15s # 规则扫描时间间隔是15秒，默认不填写是 1分钟
  scrape_timeout: 5s #超时时间
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["docker.for.mac.localhost:9093"]
scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: ["docker.for.mac.localhost:9090"]
  - job_name: "node"
    scrape_interval: 8s
    static_configs:
      - targets: ["docker.for.mac.localhost:9100"]
  - job_name: "docker"
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
  - job_name: "phanes"
    scrape_interval: 5s
    static_configs:
      - targets: ["docker.for.mac.localhost:2223"]

rule_files:
  - "/etc/prometheus/rule/*.yml"

remote_write:
  - url: http://docker.for.mac.localhost:9009/api/v1/push
# scrape_configs:
#   - job_name: "prometheus"
#     static_configs:
#       - targets: ["localhost:9090"]
#   - job_name: "node"
#     scrape_interval: 8s
#     static_configs:
#       - targets: ["localhost:9100"]
#   - job_name: "monitor"
#     static_configs:
#       - targets: ["localhost:9099"]
#   - job_name: "consul-coco"
#     consul_sd_configs:
#       - server: "localhost:8500"
#         services:
#           - coco.mgr.metrics
#           - coco.msg.metrics
#           - coco.auth.metrics
#           - coco.proxy.metrics
#           - coco.signal.metrics
#           - coco.store.metrics
#           - coco.rpt.metrics
#     relabel_configs:
#       - source_labels: [__meta_consul_service]
#         target_label: service
