global:
  resolve_timeout: 5m

route:
  receiver: webhook
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1m
  group_by: ['alertname', 'instance', 'service']
  routes:
    - receiver: webhook
      group_wait: 1s

receivers:
  - name: webhook
    webhook_configs:
      - url: 'http://127.0.0.1:9099/alert'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
