groups:
  - name: coco_down
    rules:
      - alert: ServiceDown
        expr: coco_service_up_count == 0
        for: 10s
        annotations:
          summary: "Instance {{ $labels.service }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 10 second."
