groups:
  - name: node_down
    rules:
      - alert: InstanceDown
        expr: sum by(instance) (up{service="coco.rpt.metrics"}) > 1
        for: 1m
        labels:
          user: test
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
